version: '3.2'

services:
  postgresql:
    image: postgres:14
    ports:
      - "55432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=springapp
      - POSTGRES_USER=springapp
      - POSTGRES_PASSWORD=springpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 15s
      timeout: 30s
      retries: 3

volumes:
  postgresql:
    driver: local